name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
categories:
  - title: 🚀 Features
    label: enhancement
  - title: ":beetle: Bug Fixes"
    label: bug
  - title: ":page_facing_up: Documentation"
    label: documentation
template: |
  ## Changes since $PREVIOUS_TAG
  $CHANGES
  ## Contributors

  $CONTRIBUTORS
